### ISSUE TITLE
RG405V Wake Device buttons?

### ISSUE THREAD

**Issue by DSCustoms** [TheGammaSqueeze/GammaOS#153]
In the settings menu, none of the options for "Wake Device" work except the volume buttons. At least having the Home button on the front to wake the device would be useful.  Even the Lift to wake option in the display doesn't work. 

All latest software installed yesterday.

**Comment by TheGammaSqueeze** [comment]
This will not be fixed due to the fact that I have made core changes to the underlying Android OS to disable any bluetooth/external inputs from waking the device.

As we simulate the xbox contriller connected via bluetooth, this was an issue for others who had issues with the device waking when travelling, and having a drained battery as a result.
