### ISSUE TITLE
RG505

### ISSUE THREAD

**Issue by loki666** [TheGammaSqueeze/GammaOS#2]
Are you planning to make this works for the RG505?

**Comment by rodrif24** [comment]
I would love it to be ported, if necessary I can serve with testing on my console

**Comment by vibraniumdroid** [comment]
I'm also willing to help with any sort of testing

**Comment by TheGammaSqueeze** [comment]
Thanks for your interest, I hope to port to the RG505 if someone sends me one for development.

**Comment by loki666** [comment]
> Thanks for your interest, I hope to port to the RG505 if someone sends me one for development.

Or you could open source the changes you made to Lineage OS (as you should) so someone could try it on RG505.
Probably only the display parameters needs to be changed for the RG505

**Comment by TheGammaSqueeze** [comment]
The issue isn't the open source part, it's how the 505 accepts the image I build from the GSI. The same recompiled GSI image I use for the 405m, causes a boot loop on the 505. The GSi itself is linked in the readme, I'm using this instead of building from source. That link has links to the LineageOS source.

**Comment by TheGammaSqueeze** [comment]
In fact, you can install LineageOS easily, without modification by using the GSI.

You will require an unlocked bootloader.
Grab an extracted GSI 19.1x non vndklite.

Extract it so that you have the .img file

Flash using fastboot.

adb reboot fastboot
fastboot flash system systemimagenamehere.img
fastboot format userdata
fastboot reboot

**Comment by loki666** [comment]
So andyyan GSIs are working fine on the 405m, but bootloop on the 505 ?

**Comment by vibraniumdroid** [comment]
> In fact, you can install LineageOS easily, without modification by using the GSI.
> 
> You will require an unlocked bootloader. Grab an extracted GSI 19.1x non vndklite.
> 
> Extract it so that you have the .img file
> 
> Flash using fastboot.
> 
> adb reboot fastboot fastboot flash system systemimagenamehere.img fastboot format userdata fastboot reboot
> 
> I take no responsibility if something goes wrong, you will need to use the 505 unbricker if you want to go back to stock.
> 
> https://youtube.com/watch?v=A5Ut4W95Z-Q&feature=share8

I've tried this, but regardless of what image I use or whether I try to flash it to system or system_a, I get 

> FAILED (remote: 'Write img fail!')

I guess I'm stuck on rooted stock for the time being

**Comment by TheGammaSqueeze** [comment]
I have one on the way now, will hopefully get this ported over soon.
