### ISSUE TITLE
Switch to interactive CPU governor

### ISSUE THREAD

**Issue by hoaxlayer** [TheGammaSqueeze/GammaOS#60]
The release notes for v1.3.3 state that the governor in use is currently set to use the "performance" governor.
However, this is not ideal as it can lead to wasteful battery drain when the device is idling or during low CPU usage.

Switching to the "interactive" governor is much better suited for this type of devices and use cases, where it can lead to better battery life and no loss in performance as the CPU frequency scales rapidly to meet the usage demand of whatever program the user is running.

More info can be found in Android's documentation for governors:
https://android.googlesource.com/kernel/common/+/a7827a2a60218b25f222b54f77ed38f57aebe08b/Documentation/cpu-freq/governors.txt

**Comment by dfreivald** [comment]
I take it you haven't played an emulator using "interactive" governor on any of these devices? Interactive governor has always been terrible on all these low powered handhelds, due to the nature of emulation system load swings wildly, and interactive governor can't ramp up fast enough to not cause hitching or stutters on any emulators that need more than than the smallest amount of CPU.

Moving away from the interactive governor is what helped fix the RP3+ performance issues, and is another reason JELOS works better when switching certain systems to use the performance governor. https://youtu.be/lcOSTcfLuL8?t=580
